# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ce8e70986854407ee4d1ae25e05dc244a0387e02b08fb3a6357a24c57359feb50b33888027b425f32b5e2b8f9e17cf021c4b4228d2a137861683ee6569c80b5

test:
  secret_key_base: 00cd4358cc1499456dab7f81517334ad253ebfda5dc5d34aa099014eef1dd7daad8e49ab2903049df80554d4b7bcb36956e4b689ba3d917e89098e6c569b3ed5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
